### PR TITLE
Add --accept-invalid-ssl-certificate option.

### LINKED ISSUE #42: When importing logs, if --url= is set to HTTP url and Piwik is forced to use SSL then importing logs fails
When [importing logs in Piwik](http://piwik.org/docs/log-analytics-tool-how-to/) and when Piwik is configured to use [SSL by default](http://piwik.org/faq/how-to/faq_91/), if you specify `--url=http://piwik.example.org` then Piwik will fail with this error:

```
2014-11-20 11:40:10,643: [DEBUG] Error when connecting to Piwik: <urlopen error Piwik returned an invalid response: <!DOCTYPE html>
```

The solution is to set the `--url` parameter to `https://....` when importing logs.

To fix this issue, we could maybe detect the URL redirect from HTTP to HTTPS and make Log importer detect that HTTPS should be used.

Migrated from piwik/piwik#6699

### PR DESCRIPTION
**Pull request by smarsching**
This option allows a user to ignore certificate validation problems when connecting to the Piwik server. This is useful when the server uses a self-signed or otherwise invalid certificate, but obviously should only be used when the connection can be trusted.

This PR should resolve #42 and #138.

This PR implements the new --accept-invalid-ssl-certificate option in a slightly different way than suggested in #42: Instead of messing around with internal functions of the `ssl` module, it only uses public API by creating an SSL context using the default options, disabling validation for this context instance, and then passing this context to `urllib2` (or more precisely `HTTPSHandler`). This is also the way suggested by the Python documentation and - in contrast to the way suggested in #42 - should also work with Python 3.

### CODE REVIEW

**Comment by mattab** [comment]
Hi @smarsching - thanks for the pull request! It works and fixes https://github.com/piwik/piwik-log-analytics/issues/138

**Comment by mattab** [comment]
FYI https://github.com/piwik/piwik-log-analytics/issues/42 was not fixed, as it's a different issue (where force_ssl=1 is used, then importing logs specifying http:// will not work)

**Comment by mattab** [comment]
@smarsching 
Unfortunately it seems this change actually broke the log importer in some cases. please see our build results here: https://travis-ci.org/piwik/piwik/jobs/315001887

```
There were 14 errors:

1) Piwik\Tests\System\ArchiveCronTest

Failed to setup fixture: log importer failed: 2017-12-11 20:55:26,783: [DEBUG] Accepted hostnames: all

2017-12-11 20:55:26,783: [DEBUG] Piwik Tracker API URL is: http://localhost/tests/PHPUnit/proxy/

2017-12-11 20:55:26,783: [DEBUG] Piwik Analytics API URL is: http://localhost/tests/PHPUnit/proxy/

2017-12-11 20:55:26,783: [DEBUG] No token-auth specified

2017-12-11 20:55:26,783: [DEBUG] No credentials specified, reading them from "/home/travis/build/piwik/piwik/config/config.ini.php"

2017-12-11 20:55:26,876: [DEBUG] Authentication token token_auth is: 3db1fa6860c3ef85e06ac06661aba0d1

2017-12-11 20:55:26,876: [DEBUG] Resolver: static

Traceback (most recent call last):

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 2527, in <module>

    resolver = config.get_resolver()

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 1080, in get_resolver

    return StaticResolver(self.options.site_id)

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 1522, in __init__

    'SitesManager.getSiteFromId', idSite=self.site_id

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 1505, in call_api

    return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 1455, in _call_wrapper

    response = func(*args, **kwargs)

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 1439, in _call_api

    res = Piwik._call('/', final_args, url=url)

  File "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py", line 1390, in _call

    urllib2.HTTPSHandler(context=ssl_context))

TypeError: __init__() got an unexpected keyword argument 'context'

command used: python2.6 "/home/travis/build/piwik/piwik/misc/log-analytics/import_logs.py" -ddd --url="http://localhost/tests/PHPUnit/proxy/" --idsite="1" --enable-testmode --recorders="1" --recorder-max-payload-size="1" "/home/travis/build/piwik/piwik/tests/resources/access-logs/fake_logs.log" 2>&1
```


---> Would be awesome if you could take a look and possibly issue a new pull request to fix this regression?

**Comment by smarsching** [comment]
Thanks for the heads-up. My guess is that it is an issue with Python 2.6 (I only tested it with 2.7). I will check this and get back to you.

**Comment by smarsching** [comment]
My suspicion was right, the `context` parameter of the `HTTPSHandler` constructor was first introduced in Python 2.7.9 (this was when they changed the default behavior so that certificates are validated). I will soon create a PR that adds a check whether we are running on Python >=2.7.9 and only passes the context in this case.

**Comment by smarsching** [comment]
I just created PR #200, which should fix this problem.

**Pull request merged**
